// Generated by CoffeeScript 1.9.3
(function() {
  var main, util;

  util = require('util');

  main = function() {
    return util.log("Hello, World!");
  };

  module.exports = {
    main: main
  };

}).call(this);
