// Generated by CoffeeScript 1.9.3
(function() {
  var Crackers, exec, log, main, syntax;

  Crackers = require('./crackers');

  exec = require('./exec');

  log = require('./log');

  syntax = function() {
    log.syntax("Syntax: crackers [-h] [-v] directoryName");
    log.syntax("        -h,--help         This help output");
    log.syntax("        -v,--verbose      Verbose output");
    return process.exit(1);
  };

  main = function() {
    var args, crackers, directoryName;
    args = require('minimist')(process.argv.slice(2), {
      boolean: ['h', 'v'],
      alias: {
        help: 'h',
        verbose: 'v'
      }
    });
    if (args.help || args._.length !== 1) {
      syntax();
    }
    log.setVerbose(args.verbose);
    directoryName = args._[0];
    crackers = new Crackers;
    return crackers.update({
      dir: directoryName
    });
  };

  module.exports = {
    main: main
  };

}).call(this);
