// Generated by CoffeeScript 1.9.3
(function() {
  var ComicGenerator;

  ComicGenerator = (function() {
    function ComicGenerator() {}

    ComicGenerator.prototype.generate = function() {};

    return ComicGenerator;

  })();

  module.exports = ComicGenerator;

}).call(this);
