// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = {
    ROOT_FILENAME: "root.crackers",
    INDEX_FILENAME: 'index.html',
    IMAGES_DIR: 'images',
    TEMP_UNPACK_DIR: 'unpackTmp'
  };

}).call(this);
