// Generated by CoffeeScript 1.9.3
(function() {
  var ComicGenerator, Crackers, IndexGenerator, MobileGenerator, Unpacker, cfs, constants, fs, log, path, ref, touch, wrench;

  cfs = require('./cfs');

  constants = require('./constants');

  fs = require('fs');

  log = require('./log');

  path = require('path');

  touch = require('touch');

  wrench = require('wrench');

  ref = require('./generators'), ComicGenerator = ref.ComicGenerator, IndexGenerator = ref.IndexGenerator, MobileGenerator = ref.MobileGenerator;

  Unpacker = require('./unpacker');

  Crackers = (function() {
    function Crackers() {}

    Crackers.prototype.error = function(text) {
      log.error(text);
      return false;
    };

    Crackers.prototype.update = function(args) {
      var comicDir, comicGenerator, file, filesToUnpack, i, imageDir, imageDirPieces, imageDirs, indexDir, indexDirSeen, indexDirs, indexGenerator, j, k, l, len, len1, len2, len3, m, mobileGenerator, nextDir, nextParent, nextParsed, parent, parsed, unpackDir, unpackFile;
      this.force = args.force;
      this.download = args.download;
      this.updateDir = path.resolve('.', args.dir);
      if (!cfs.dirExists(this.updateDir)) {
        return this.error("'" + this.updateDir + "' is not an existing directory.");
      }
      log.verbose("updateDir: " + this.updateDir);
      this.rootDir = cfs.findParentContainingFilename(this.updateDir, constants.ROOT_FILENAME);
      if (!this.rootDir) {
        this.rootDir = this.updateDir;
        log.warning("crackers root not found (" + constants.ROOT_FILENAME + " not detected in parents).");
      }
      log.verbose("rootDir  : " + this.rootDir);
      cfs.touchRoot(this.rootDir);
      filesToUnpack = (function() {
        var j, len, ref1, results;
        ref1 = cfs.listDir(this.updateDir);
        results = [];
        for (j = 0, len = ref1.length; j < len; j++) {
          file = ref1[j];
          if (file.match(/\.cb[rz]$/)) {
            results.push(path.resolve(this.updateDir, file));
          }
        }
        return results;
      }).call(this);
      for (j = 0, len = filesToUnpack.length; j < len; j++) {
        unpackFile = filesToUnpack[j];
        parsed = path.parse(unpackFile);
        unpackDir = cfs.join(parsed.dir, parsed.name);
        log.verbose("Processing " + unpackFile + " ...");
        this.unpack(unpackFile, unpackDir, this.force);
      }
      imageDirs = (function() {
        var k, len1, ref1, results;
        ref1 = cfs.listDir(this.updateDir);
        results = [];
        for (k = 0, len1 = ref1.length; k < len1; k++) {
          file = ref1[k];
          if (file.match(/images$/)) {
            results.push(path.resolve(this.updateDir, file));
          }
        }
        return results;
      }).call(this);
      for (i = k = 0, len1 = imageDirs.length; k < len1; i = ++k) {
        imageDir = imageDirs[i];
        parsed = path.parse(imageDir);
        if (parsed.dir) {
          comicDir = parsed.dir;
          parent = path.parse(parsed.dir);
          nextDir = "";
          if (i + 1 < imageDirs.length) {
            nextParsed = path.parse(imageDirs[i + 1]);
            if (nextParsed.dir) {
              nextParent = path.parse(nextParsed.dir);
              if (nextParent.name && (parent.dir === nextParent.dir)) {
                nextDir = "../" + nextParent.name;
              }
            }
          }
          comicGenerator = new ComicGenerator(this.rootDir, comicDir, nextDir, this.force);
          comicGenerator.generate();
        }
      }
      indexDirSeen = {};
      for (l = 0, len2 = imageDirs.length; l < len2; l++) {
        imageDir = imageDirs[l];
        imageDirPieces = imageDir.split(path.sep);
        imageDirPieces.pop();
        imageDirPieces.pop();
        while (imageDirPieces.length > 1) {
          indexDir = cfs.join.apply(null, imageDirPieces);
          indexDirSeen[indexDir] = true;
          if (indexDir === this.rootDir) {
            break;
          }
          imageDirPieces.pop();
        }
      }
      indexDirs = Object.keys(indexDirSeen).sort().reverse();
      for (m = 0, len3 = indexDirs.length; m < len3; m++) {
        indexDir = indexDirs[m];
        indexGenerator = new IndexGenerator(this.rootDir, indexDir, this.force, this.download);
        indexGenerator.generate();
      }
      mobileGenerator = new MobileGenerator(this.rootDir);
      mobileGenerator.generate();
      return true;
    };

    Crackers.prototype.unpack = function(file, dir, force) {
      var indexFilename, unpackRequired, unpacker, valid;
      if (!cfs.prepareComicDir(dir)) {
        return false;
      }
      indexFilename = cfs.join(dir, constants.INDEX_FILENAME);
      unpackRequired = force.unpack;
      if (cfs.newer(file, indexFilename)) {
        unpackRequired = true;
      }
      if (unpackRequired) {
        log.progress("Unpacking " + file + " into " + dir);
        unpacker = new Unpacker(file, dir);
        valid = unpacker.unpack();
        unpacker.cleanup();
        if (!valid) {
          return false;
        }
      } else {
        log.verbose("Unpack not required: (" + file + " older than " + indexFilename + ")");
      }
      return true;
    };

    Crackers.prototype.findArchives = function(filenames) {
      var archives, cbrRegex, filename, fn, j, k, len, len1, list, stat;
      archives = [];
      cbrRegex = /\.cb[rz]$/i;
      for (j = 0, len = filenames.length; j < len; j++) {
        filename = filenames[j];
        if (!fs.existsSync(filename)) {
          log.warning("Ignoring nonexistent filename: " + filename);
          continue;
        }
        stat = fs.statSync(filename);
        if (stat.isFile()) {
          if (filename.match(cbrRegex)) {
            archives.push(filename);
          }
        } else if (stat.isDirectory()) {
          list = cfs.listDir(filename);
          for (k = 0, len1 = list.length; k < len1; k++) {
            fn = list[k];
            fn = path.resolve(filename, fn);
            if (fn.match(cbrRegex)) {
              archives.push(fn);
            }
          }
        } else {
          log.warning("Ignoring unrecognized filename: " + filename);
        }
      }
      return archives;
    };

    Crackers.prototype.processTemplate = function(template, name) {
      var keys, match, output;
      keys = {};
      match = name.match(/^(\D*)(\d+)/);
      if (match) {
        keys.name = match[1];
        keys.name = keys.name.replace(/[\. ]+$/, '');
        keys.issue = match[2];
      } else {
        return name;
      }
      output = template;
      output = output.replace(/\{([^\}]+)\}/g, function(match, key) {
        var pieces, places, ref1, ref2, replacement;
        replacement = (ref1 = keys[key]) != null ? ref1 : "";
        pieces = key.split(/\./);
        if (pieces.length > 1) {
          replacement = (ref2 = keys[pieces[0]]) != null ? ref2 : "";
          places = parseInt(pieces[1]);
          if (replacement.length < places) {
            replacement = "00000000000000000000000000000" + replacement;
            replacement = replacement.substr(replacement.length - places);
          }
        }
        return replacement;
      });
      output = output.replace(/^[ \/]+/, '');
      output = output.replace(/[ \/]+$/, '');
      return output;
    };

    Crackers.prototype.organize = function(args) {
      var archives, dst, dstDir, j, len, madeDir, mkdirCmd, mvCmd, parsed, processed, src, template;
      archives = this.findArchives(args.filenames);
      if (archives.length === 0) {
        log.warning("organize: Nothing to do!");
        return;
      }
      template = args.template;
      if (!template) {
        template = "{name}/{issue.3}";
      }
      template = template.replace(/\\/g, '/');
      template = template.replace(/\/\//g, '/');
      template = template.replace(/\//g, path.sep);
      madeDir = {};
      mvCmd = "mv";
      if (process.platform === 'win32') {
        mvCmd = "rename";
      }
      mkdirCmd = "mkdir -p";
      if (process.platform === 'win32') {
        mkdirCmd = "mkdir";
      }
      for (j = 0, len = archives.length; j < len; j++) {
        src = archives[j];
        parsed = path.parse(src);
        processed = this.processTemplate(template, parsed.name);
        dst = cfs.join(parsed.dir, processed) + parsed.ext;
        parsed = path.parse(dst);
        dstDir = parsed.dir;
        if (!madeDir[dstDir] && !cfs.dirExists(dstDir)) {
          madeDir[dstDir] = true;
          if (args.execute) {
            console.log(" Mkdir: \"" + dstDir + "\"");
            wrench.mkdirSyncRecursive(dstDir);
          } else {
            console.log(mkdirCmd + " \"" + dstDir + "\"");
          }
        }
        if (src === dst) {
          if (args.execute) {
            console.log("Skip  : \"" + src + "\"");
          }
        } else {
          if (args.execute) {
            console.log("Rename: \"" + src + "\"");
            console.log("    to: \"" + dst + "\"");
            fs.renameSync(src, dst);
          } else {
            console.log(mvCmd + " \"" + src + "\" \"" + dst + "\"");
          }
        }
      }
    };

    Crackers.prototype.cleanup = function(args) {
      var archives, cmd, filename, j, len;
      archives = this.findArchives(args.filenames);
      if (archives.length === 0) {
        log.warning("cleanup: Nothing to do!");
        return;
      }
      cmd = "rm";
      if (process.platform === 'win32') {
        cmd = "del";
      }
      for (j = 0, len = archives.length; j < len; j++) {
        filename = archives[j];
        if (args.execute) {
          console.log("Removing: " + filename);
          fs.unlinkSync(filename);
        } else {
          console.log(cmd + " \"" + filename + "\"");
        }
      }
    };

    return Crackers;

  })();

  module.exports = Crackers;

}).call(this);
