// Generated by CoffeeScript 1.9.3
(function() {
  var commandMissing, commandPaths, fs, log, name, path, spawnSync, which;

  fs = require('fs');

  log = require('./log');

  path = require('path');

  spawnSync = require('child_process').spawnSync;

  which = require('which');

  commandPaths = {
    unzip: null,
    unrar: null,
    convert: null,
    composite: null
  };

  if (process.platform === 'win32') {
    commandPaths.unzip = path.resolve(__dirname, "../wbin/unzip.exe");
    commandPaths.unrar = path.resolve(__dirname, "../wbin/unrar.exe");
    commandPaths.convert = path.resolve(__dirname, "../wbin/convert.exe");
    commandPaths.composite = path.resolve(__dirname, "../wbin/composite.exe");
  } else {
    for (name in commandPaths) {
      try {
        commandPaths[name] = which.sync(name);
      } catch (_error) {

      }
    }
  }

  commandMissing = false;

  for (name in commandPaths) {
    path = commandPaths[name];
    if (path === null) {
      log.error("crackers requires " + name + " to be installed.");
      commandMissing = true;
    }
  }

  if (commandMissing) {
    process.exit(1);
  }

  log.verbose("commandPaths: " + (JSON.stringify(commandPaths, null, 2)));

  module.exports = function(cmdName, args, workingDir) {
    var commandPath;
    commandPath = commandPaths[cmdName];
    if (!commandPath) {
      log.error("Attempting to run unknown external command '" + cmdName + "'");
      process.exit(1);
    }
    log.verbose("executing external command " + cmdName + " (" + commandPath + "), args [ " + args + " ], workingDir " + workingDir);
    spawnSync(commandPath, args, {
      cwd: workingDir,
      stdio: 'inherit'
    });
  };

}).call(this);
