// Generated by CoffeeScript 1.9.3
(function() {
  var IndexGenerator;

  IndexGenerator = (function() {
    function IndexGenerator() {}

    IndexGenerator.prototype.generate = function() {};

    return IndexGenerator;

  })();

  module.exports = IndexGenerator;

}).call(this);
