// Generated by CoffeeScript 1.9.3
(function() {
  var fs;

  fs = require('fs');

  module.exports = function(name, replacements) {
    var i, len, line, outputText, rawTemplate, templateFilename, templateLines;
    templateFilename = __dirname + ("/../templates/" + name + ".html");
    if (!fs.existsSync(templateFilename)) {
      return "";
    }
    rawTemplate = fs.readFileSync(templateFilename);
    templateLines = String(rawTemplate).split(/(?:\n|\r\n|\r)/g);
    outputText = "";
    for (i = 0, len = templateLines.length; i < len; i++) {
      line = templateLines[i];
      line = line.replace(/#inject\{([^\}]+)\}/g, function(match, key) {
        var ref;
        return (ref = replacements[key]) != null ? ref : "";
      });
      outputText += line;
      outputText += "\n";
    }
    return outputText;
  };

}).call(this);
