browserify = require 'browserify'
coffeeify = require 'coffeeify'
uglifyify = require 'uglifyify'

Markdown = require 'remarkable'

fs = require 'fs'
path = require 'path'
{spawn} = require 'child_process'
util = require 'util'

coffeeName = 'coffee'
if process.platform == 'win32'
  coffeeName += '.cmd'

buildUI = (callback) ->
  # equal of command line $ "browserify --debug -t coffeeify ./src/main.coffee > bundle.js "
  productionBuild = (process.env.NODE_ENV == 'production')
  opts = {
    extensions: ['.coffee']
  }
  if not productionBuild
    opts.debug = true
  b = browserify opts
  b.add './src/ui/main.coffee'
  b.transform coffeeify
  if productionBuild
    b.transform { global: true, ignore: ['**/main.*'] }, uglifyify
  b.bundle (err, result) ->
    if not err
      fs.writeFile "build/templates/ui.js", result, (err) ->
        if not err
          util.log "UI compilation finished."
          callback?()
        else
          util.log "UI bundle write failed: " + err
    else
      util.log "UI compilation failed: " + err

buildMarkdown = (callback) ->
  parser = new Markdown {
    # options
  }
  files = fs.readdirSync('./markdown')

  header = """
    # This file is autogenerated. See Cakefile.

    React = require 'react'
    {span} = require './tags'

    markdowns =
  """

  footer = """
    class MarkdownSpan extends React.Component
      constructor: (props) ->
        super props

      render: ->
        html = markdowns[@props.name] ? ""
        return span {
          dangerouslySetInnerHTML:
            __html: html
        }

    module.exports = MarkdownSpan
  """

  markdownSpan = header + "\n"

  for filename in files
    parsed = path.parse(filename)
    markdown = fs.readFileSync("./markdown/#{filename}")
    html = parser.render(String(markdown))
    markdownSpan += "  #{parsed.name}: " + JSON.stringify(html) + "\n"
  markdownSpan += "\n" + footer
  fs.writeFileSync("./src/ui/MarkdownSpan.coffee", markdownSpan)
  util.log "MarkdownSpan generation finished."
  callback?()

buildTool = (callback) ->
  coffee = spawn coffeeName, ['-c', '-o', 'build', 'src/tool']
  coffee.stderr.on 'data', (data) ->
    process.stderr.write data.toString()
    process.exit(-1)
  coffee.stdout.on 'data', (data) ->
    print data.toString()
  coffee.on 'exit', (code) ->
    util.log "Tool compilation finished."
    callback?() if code is 0

# Adapted from 'wrench' module
readdir = (baseDir) ->
  baseDir = baseDir.replace(/\/$/, '')

  readdirSyncRecursive = (baseDir) ->
    files = []
    isDir = (fname) ->
      if fs.existsSync(path.join(baseDir, fname))
        return fs.statSync( path.join(baseDir, fname) ).isDirectory()
      return false
    prependBaseDir = (fname) ->
      return path.join(baseDir, fname)

    curFiles = fs.readdirSync(baseDir)
    nextDirs = curFiles.filter(isDir)
    curFiles = curFiles.map(prependBaseDir)

    files = files.concat(curFiles)

    while nextDirs.length > 0
      files = files.concat( readdirSyncRecursive(path.join(baseDir, nextDirs.shift())) )

    return files

  # convert absolute paths to relative
  fileList = readdirSyncRecursive(baseDir).map (val) ->
    return path.relative(baseDir, val)

  return fileList

scan = (filename) ->
  foundBadIndent = false
  lines = String(fs.readFileSync("src/#{filename}")).split(/\n/)
  prevIndent = 0
  for line, index in lines
    line = line.replace(/[\r]/, '')
    pageNumber = index+1

    indent = 0
    if matches = line.match(/^(\s*)/)
      indent = matches[1].length

    if (prevIndent > 0) and (indent >= prevIndent+4)
      console.error "ERROR: Found double indent: #{filename}:#{pageNumber} (#{prevIndent} -> #{indent})"
      foundBadIndent = true
    prevIndent = indent
  return foundBadIndent

findDoubleIndents = (callback) ->
  files = readdir('src')
  foundBadIndent = false
  for file in files
    if file.match(/.coffee$/)
      if scan(file)
        foundBadIndent = true
  if not foundBadIndent
    util.log "No double indents found."
    callback?()

task 'build', 'build JS bundle', (options) ->
  findDoubleIndents ->
    buildTool ->
      buildMarkdown ->
        buildUI ->
