# This file is autogenerated. See Cakefile.

React = require 'react'
{span} = require './tags'

markdowns =
  welcome: "<h1>Welcome</h1>\n<hr>\n<p>This is some markdown.</p>\n<pre><code>This is some code?\nI hope it is.\n</code></pre>\n<p>Some more prose here.</p>\n<hr>\n<p>line between this <strong>bold</strong> shit</p>\n"

class MarkdownSpan extends React.Component
  constructor: (props) ->
    super props

  render: ->
    html = markdowns[@props.name] ? ""
    return span {
      dangerouslySetInnerHTML:
        __html: html
    }

module.exports = MarkdownSpan