// Generated by CoffeeScript 1.9.3
(function() {
  var currentSort, prevUrl, recentCover, sorts;

  if (isMobile.any) {
    prevUrl = "#inject{prev}";
    if (prevUrl) {
      $("body").append("<a class=\"box indexbox\" href=\"" + prevUrl + "\"></a>");
    }
  }

  recentCover = false;

  currentSort = -1;

  sorts = [
    {
      name: 'Alphabetical',
      func: function(a, b) {
        var ca, cb;
        ca = $(a).data('title');
        cb = $(b).data('title');
        if (ca < cb) {
          return -1;
        }
        if (ca > cb) {
          return 1;
        }
        return 0;
      }
    }, {
      name: 'Recent',
      func: function(a, b) {
        var ca, cb;
        ca = parseInt($(a).data('timestamp'));
        cb = parseInt($(b).data('timestamp'));
        if (ca < cb) {
          return 1;
        }
        if (ca > cb) {
          return -1;
        }
        return 0;
      }
    }
  ];

  window.sorts = sorts;

  window.sort = function(how) {
    var divs;
    currentSort = how;
    $('.sortowned').remove();
    if (sorts[currentSort].pre) {
      sorts[currentSort].pre();
    }
    divs = $('.sorted');
    divs.sort(sorts[currentSort].func);
    if (sorts[currentSort].post) {
      sorts[currentSort].post();
    }
    $('#entries').append(divs);
    $('#sortorder').text(sorts[currentSort].name);
  };

  window.nextsort = function(event) {
    if (event != null) {
      event.preventDefault();
    }
    window.sort((currentSort + 1) % sorts.length);
  };

  window.resort = function(event) {
    if (event != null) {
      event.preventDefault();
    }
    window.sort(currentSort);
  };

  window.toggleRecentCover = function(event) {
    var attrName, name;
    if (event != null) {
      event.preventDefault();
    }
    attrName = 'data-cover';
    name = 'First Cover';
    recentCover = !recentCover;
    if (recentCover) {
      attrName = 'data-recentcover';
      name = 'Newest Cover';
    }
    $('.sorted img').each(function() {
      var cover;
      cover = $(this).attr(attrName);
      return $(this).attr('src', cover);
    });
    return $('#togglerecent').text(name);
  };

  $(function() {
    return nextsort();
  });

}).call(this);
