// Generated by CoffeeScript 1.9.3
(function() {
  var currentSort, prevUrl, recentCover, sorts;

  if (isMobile.any) {
    prevUrl = "#inject{prev}";
    if (prevUrl) {
      $("body").append("<a class=\"box prevbox\" href=\"" + prevUrl + "\"></a>");
    }
  }

  recentCover = false;

  currentSort = -1;

  sorts = [
    {
      name: 'Alphabetical',
      func: function(a, b) {
        var ca, cb;
        ca = $(a).attr('data-title');
        cb = $(b).attr('data-title');
        if (ca < cb) {
          return -1;
        }
        if (ca > cb) {
          return 1;
        }
        return 0;
      }
    }, {
      name: 'Recent',
      func: function(a, b) {
        var ca, cb;
        ca = parseInt($(a).attr('data-timestamp'));
        cb = parseInt($(b).attr('data-timestamp'));
        if (ca < cb) {
          return 1;
        }
        if (ca > cb) {
          return -1;
        }
        return 0;
      }
    }
  ];

  window.nextsort = function(event) {
    var divs;
    if (event != null) {
      event.preventDefault();
    }
    currentSort = (currentSort + 1) % sorts.length;
    divs = $('.sorted');
    divs.sort(sorts[currentSort].func);
    $('#entries').append(divs);
    $('#sortorder').text(sorts[currentSort].name);
  };

  window.toggleRecentCover = function(event) {
    var attrName, name;
    if (event != null) {
      event.preventDefault();
    }
    attrName = 'data-cover';
    name = 'First Cover';
    recentCover = !recentCover;
    if (recentCover) {
      attrName = 'data-recentcover';
      name = 'Newest Cover';
    }
    $('.sorted img').each(function() {
      var cover;
      cover = $(this).attr(attrName);
      return $(this).attr('src', cover);
    });
    return $('#togglerecent').text(name);
  };

  $(function() {
    return nextsort();
  });

}).call(this);
