// Generated by CoffeeScript 1.9.3
(function() {
  var prevUrl;

  if (isMobile.any) {
    prevUrl = "#inject{prev}";
    if (prevUrl) {
      $("body").append("<a class=\"prevbox\" href=\"" + prevUrl + "\">&nbsp;</a>");
    }
  }

}).call(this);
