// Generated by CoffeeScript 1.9.3
(function() {
  $(function() {
    var generator, loadLocal, root;
    loadLocal = function(path) {
      var element;
      element = document.createElement("script");
      element.src = path;
      return document.body.appendChild(element);
    };
    generator = "#inject{generator}";
    root = "#inject{root}";
    if (generator && root) {
      loadLocal(root + "/local.js");
      return loadLocal(root + "/local." + generator + ".js");
    }
  });

}).call(this);
