module.exports =
  DEFAULT_TITLE: "Crackers"
  ROOT_FILENAME: "root.crackers"
  META_FILENAME: 'meta.crackers'
  INDEX_FILENAME: 'index.html'
  COVER_FILENAME: 'cover.png'
  IMAGES_DIR: 'images'
  TEMP_UNPACK_DIR: 'unpackTmp'
  COVER_WIDTH: 150
  SPAM_SIZE_TOLERANCE: 0.25
